controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

acceuil:
    path: /
    controller: App\Controller\HomeController::number

contact:
    path: /contact
    controller: App\Controller\ContactController::number

a-propos:
    path: /a-propos
    controller: App\Controller\AproposController::number

user:
    path: /user
    controller: App\Controller\UserController::list